Fix capitol image
enthought/chaco pull request #880
Opened 2023-04-03 01:29 UTC by homosapien-lcy

After the capitol.jpg moved, chaco/examples/user_guide/plot_types/create_plot_snapshots is broken, use importlib.resources to find the image for loading to fix this

2023-04-03 01:57 UTC, homosapien-lcy commented
closes #879

2023-04-06 07:00 UTC, corranwebster requested changes
This breaks on 3.7 and 3.8.

See https://github.com/enthought/pyface/blob/0fb8373b4dbb5e104d3120e88590dbf964865245/pyface/tests/test_pil_image.py#L14-L20 for an example of how to handle this sort of use of importlib across many Python versions

2023-04-10 07:07 UTC, homosapien-lcy commented on examples/user_guide/plot_types/create_plot_snapshots.py
> +    filename = resources.files(
Thanks for the tip, just add both importlibs

2023-04-17 08:26 UTC, corranwebster commented on examples/user_guide/plot_types/create_plot_snapshots.py
>      image_source = ImageData.fromfile(filename)
Typically you want to have this in a with statement something like:
```
resource = files(...)
with as_file(resource) as filename:
    ...
```

2023-04-17 08:26 UTC, corranwebster requested changes
Can you please add an appropriate dependency to `importlib_resources` for Python < 3.9 here: https://github.com/enthought/chaco/blob/main/chaco/__init__.py#L19

Also a usage issue for `importlib.resources.files`.

2023-04-25 04:19 UTC, homosapien-lcy commented
> Can you please add an appropriate dependency to `importlib_resources` for Python < 3.9 here: https://github.com/enthought/chaco/blob/main/chaco/__init__.py#L19
> 
> Also a usage issue for `importlib.resources.files`.

Got it, just add a "check python3.9 then install importlib_resources" there.
Just want to clarify, what do you mean by usage issue for `importlib.resources.files`?

2023-05-04 15:32 UTC, corranwebster approved these changes

2023-05-04 15:34 UTC, corranwebster commented
> Just want to clarify, what do you mean by usage issue for `importlib.resources.files`?

Meaning it should be used in a `with` statement, which you have now done.

This should be good to merge.

2023-05-08 01:20 UTC, homosapien-lcy commented
> > Just want to clarify, what do you mean by usage issue for `importlib.resources.files`?
> 
> Meaning it should be used in a `with` statement, which you have now done.
> 
> This should be good to merge.

Thanks Corran! The merge is still block by the ci test, the good old RuntimeError Numpy... Is there anyway we can get around it?

```
RuntimeError: NumPy was built with baseline optimizations: 
(SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C AVX2) but your machine doesn't support:
(AVX2).
```

2023-05-08 08:20 UTC, merged